name: Deployment Pipeline Production

on:
  push:
    branches:
      - main

jobs:
  execute-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH Context
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Transfer Project Files
        run: |
          scp -r Dockerfile index.html ubuntu@${{ secrets.EC2_HOST }}:~/

      - name: Launch Docker Container
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} "
            sudo docker stop app-web-live || true
            sudo docker rm app-web-live || true
            sudo docker build --no-cache -t webserver-prod:latest .
            sudo docker run -d -p 80:80 --name app-web-live --restart always webserver-prod:latest
          "